### ISSUE TITLE
Colors in shell

### ISSUE THREAD

**Issue by LukasSliacky** [ei-grad/flask-shell-ipython#10]
Hello @ei-grad , 
thank you for your great project - i use it every day.
 
I have question about config file: 
Is possible to use colors in flask-shell-ipython (syntax highlighting)? 
When i am run only `ipython` commad, colors works fine, but when i run `ipython manage.py shell` color theme aren't works.

Thank you for your answer.
Lukas

**Comment by ei-grad** [comment]
Sorry for leaving this without response. Checked - currently it works. Also, [color settings](https://ipython.readthedocs.io/en/stable/config/details.html#terminal-colors) could be configured via `app.config['IPYTHON_CONFIG']`.

**Comment by ei-grad** [comment]
Got it reproduced!

**Comment by ei-grad** [comment]
Hm.. No, sorry. Just got into the basic flask shell unexpectedly.

**Comment by ei-grad** [comment]
Btw, it is not intended to be run like in your prompt. Don't run "**i**python setup.py shell". Run just `flask shell`.
