### ISSUE TITLE
Eventlet + MonkeyPatch == frozen

### ISSUE THREAD

**Issue by italomaia** [ei-grad/flask-shell-ipython#3]
I just happened to try to use this extension while having eventlet + monkeypatch with flask and socketio. The result was quite disturbing. Shell just froze/hangs. Suggestions? 

As this is a lone issue, I'll mention the author @ei-grad

**Comment by ei-grad** [comment]
Can I suggest not to use eventlet patch when running ipython shell? And also, have you tried it in ipython (or plain python interactive mode) without flask?

**Comment by italomaia** [comment]
I see "fair" written all over this suggestion. I'll see if it works. I'm monkey patching the whole before instantiating because of redis+flask-socketio.

**Comment by ei-grad** [comment]
I guess that you would need something like http://eventlet.net/doc/modules/backdoor.html if you really want to run an interactive session within a monkeypatched application context.

**Comment by ocervell** [comment]
Do you have a workaround for this ?
