### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by shlomiLan** [ei-grad/flask-shell-ipython#4]
Hi,

In the setup.py file there isn't any indication in which versions of python this package can be used. I'm using it with Python 3.6 and didn't see any problems.

Can you think/know of any issue or is it safe to add Python 3 (and maybe 2) to the setup file?

Thanks

**Comment by ei-grad** [comment]
Hi. There are no known problems on Python 2.7/3.x. Do you think `python_requires` should be added to the `setup.py`? Why?

**Comment by shlomiLan** [comment]
I'm using [this](https://pyup.io) to check my dependencies and it marks this package as not compatible with Python 3.
I think that it looks for the `classifiers` in the `setup.py` as you can see [here](https://github.com/wummel/patool/blob/master/setup.py#L217)

**Comment by ei-grad** [comment]
Though it looks for me that it is more a problem of pyup compatibility detection, it is still a good thing to add the classifiers. I published the new version on PyPI, does pyup still shows the Python 3.x compatibility problems for `flask-shell-ipython==0.3.1` ?

**Comment by shlomiLan** [comment]
It's fixed now.
Thanks
