### ISSUE TITLE
Is v. 0.4 compatible with Flask 0.12?

### ISSUE THREAD

**Issue by hectorcanto** [ei-grad/flask-shell-ipython#8]
Hi, I have a project using Flask 0.12 (Eve actually) and I installed flask-shell-ipython, which upgraded my Flask to 1.0.2. I've checked the code and I don't see any reason to request 1.0 instead of 0.12. It is possible to downgrade the requirements to 0.12? is there any reason not to support 0.12?.

Should I make a pull request or maybe it is preferable to make a fork just in case?

Thanks for your code
Héctor

**Comment by Kulv3r** [comment]
Facing the same issue here.
Please downgrade Flask requirements to 0.12.

**Comment by ei-grad** [comment]
Hi! Sorry for the long response.

No, 0.4 is not compatible with `flask<1.0` because `Flask.env` was added in 1.0. Use `pip install "flask-shell-ipython<0.4"`.

```
File "/home/ei-grad/.virtualenvs/test-flask-0.12/lib/python3.7/site-packages/flask_shell_ipython.py", line 38, in shell
    app.env,
AttributeError: 'Flask' object has no attribute 'env'
```
