### ISSUE TITLE
Version 0.3.0 removed from PyPI?

### ISSUE THREAD

**Issue by gtback** [ei-grad/flask-shell-ipython#9]
Hi @ei-grad, thanks for the great tool!

Did you happen to remove version 0.3.0 from PyPI in the last day or so? We have had builds start failing because that version is no longer available. It was a relatively easy fix (upgrading to 0.3.1 or 0.4.1, since there are no major breaking changes), but unless there is a security vulnerability in the older version, it's probably best to leave it published.

Thanks again :-)

**Comment by ThiefMaster** [comment]
Even if there is a security issue (unless it's highly critical which is certainly not the case for this package), please don't de-publish packages at all.

**Comment by ei-grad** [comment]
Sorry guys! It was really stupid, don't know why my hand jerked to remove it :-(. There was absolutely no reason.
